### ISSUE TITLE
Ñ words missing

### ISSUE THREAD

**Issue by hopsor** [kamilmielnik/fise-2#1]
Hi @kamilmielnik 

First of all thanks for sharing the dictionary. I'm building a Scrabble clone using Phoenix Framework + LiveView and I appreciated finding it. While testing your dictionary I've just realised that words with Ñ for some reason is missing.

I checked flexargentina website but I'm not able to find them. No idea why.

According to this website there are 15708 words including Ñ character:

https://www.listasdepalabras.es/c/ñ/1/palabrasconñ.htm

**Comment by kamilmielnik** [comment]
Hey @hopsor :wave: 
Thanks for reporting this!

----

I see that the website you posted uses [Wiktionary](https://es.wiktionary.org/wiki/Wikcionario:Portada) as a source. See https://es.wikwik.org/listas.htm:

> Las listas se generan a partir de 806303 palabras (de 1 a 21 letras) en el Wikcionario que tienen al menos una definición en español.

List of words in Wiktionary is not the same as list of words in FISE - some differences are expected.

----

However, words with "ñ" do seem missing (e.g. "baño").
The source of words is the same as for https://play.google.com/store/apps/details?id=com.janke.lexicabble.
I can't find "bano" or "baño" in these sources. Perhaps this issue should be reported to http://fisescrabble.org/ ?

@hopsor can you find words with "ñ" using the [official app](https://play.google.com/store/apps/details?id=com.janke.lexicabble)?

**Comment by okahn** [comment]
It looks like “ñ” is written as “1” in the word list. For example “baño” appears as as “ba1o” in both source lists.

**Comment by kamilmielnik** [comment]
> It looks like “ñ” is written as “1” in the word list. For example “baño” appears as as “ba1o” in both source lists.

Good catch, thanks!

In [previous sources "1" used to mean "ch"](https://github.com/kamilmielnik/scrabble-solver/issues/98#issuecomment-922999144). Can we be sure that the meaning of "1" is unambiguous here?

**Comment by hopsor** [comment]
hi, after a long time I'm back at this trying to figure out what's going on with the ñ issue. I'm going to do further research but apparently @okahn seems right. For instance, I'm looking at `p.txt` and I'm trying to find words starting by `pañ`.

These are the matches in the file:

```
pa1al
pa1ales
pa1alon
pa1alones
pa1anga
pa1angas
pa1era
pa1eras
pa1eria
pa1erias
pa1ero
pa1eros
pa1eta
pa1etaba
pa1etabais
pa1etabamos
pa1etaban
pa1etabas
pa1etad
pa1etada
pa1etadas
pa1etado
pa1etados
pa1etais
pa1etamos
pa1etan
pa1etando
pa1etar
pa1etara
pa1etarais
pa1etaramos
pa1etaran
pa1etaras
pa1etare
pa1etareis
pa1etaremos
pa1etaren
pa1etares
pa1etaria
pa1etariais
pa1etariamos
pa1etarian
pa1etarias
pa1etaron
pa1etas
pa1etase
pa1etaseis
pa1etasemos
pa1etasen
pa1etases
pa1etaste
pa1etasteis
pa1ete
pa1eteis
pa1etemos
pa1eten
pa1etes
pa1eto
pa1i
pa1il
pa1iles
pa1ito
pa1itos
pa1izuelo
pa1izuelos
pa1o
pa1ol
pa1olera
pa1oleras
pa1oleria
pa1olerias
pa1olero
pa1oleros
pa1oles
pa1oleta
pa1oletas
pa1olito
pa1olitos
pa1olon
pa1olones
pa1os
pa1osa
pa1osas
pa1oso
pa1osos
pa1uelo
pa1uelos
pa1usa
pa1usas
pa1uso
pa1usos
```

And this is what official Spanish dictionary shows: 

https://dle.rae.es/pañ?m=31

I think it's pretty consistent. There are a bunch of more entries in the txt files than in the rae search but I believe most of them are conjugations of the verb [pañetar](https://dle.rae.es/pañetar).

I will try to do further research but I believe we are in the right direction. What I don't understand is why the ñ is appearing as a 1 in the files. Maybe it's an encoding issue?

**Comment by kamilmielnik** [comment]
> I think it's pretty consistent.
> I will try to do further research but I believe we are in the right direction.

Let me reiterate my [previous concern](https://github.com/kamilmielnik/fise-2/issues/1#issuecomment-1195874620): 

The code that downloads and prepares the dictionary already replaces "1" with "ch": https://github.com/kamilmielnik/fise-2/blob/ef7b43b/download.js#L42.
So, is the meaning of `1` different in different files? Or is it ambiguous?

> What I don't understand is why the ñ is appearing as a 1 in the files. Maybe it's an encoding issue?

To me it looks like it's done on purpose, perhaps to avoid encoding issues.
But if the character turns out to be ambiguous then this guess does not make sense.

**Comment by michelc** [comment]
I think you can assume "1" is only for the "ñ" char as "ch" and "ll" (and "rr" ?) were removed in 2010 by the Royal Spanish Academy.

> The digraphs ⟨ch⟩ and ⟨ll⟩ were considered single letters of the alphabet from 1754 to 2010

https://en.wikipedia.org/wiki/Spanish_orthography#Alphabet_in_Spanish

Also according to Wikipedia, there are exactly 27 letters in the spanish alphabet.

**Comment by kamilmielnik** [comment]
I updated the dictionary with "1" replaced as "ñ".
Here's the new version: https://github.com/kamilmielnik/scrabble-dictionaries/blob/master/spanish/fise-2.txt

Thanks everyone!
